import crypto from "crypto";
import { config } from "../config";

// AES-256-GCM secret storage for provider keys and per-user OAuth tokens. The
// key is derived from JWT_SECRET, which production validation requires to be a
// non-placeholder value of at least 32 characters. Docker deployments persist
// an autogenerated JWT secret, so encrypted data remains readable after a
// restart.
const KEY_DERIVATION_SALT = "excalidash-ai-key-v1";
const ENC_PREFIX = "aesgcm";

const deriveKey = (): Buffer =>
  crypto.scryptSync(config.jwtSecret, KEY_DERIVATION_SALT, 32);

/**
 * Encrypt a plaintext secret. Output format:
 *   aesgcm$<iv-base64>$<authTag-base64>$<ciphertext-base64>
 * so it is self-describing and safe to store in a TEXT column.
 */
export const encryptSecret = (plaintext: string): string => {
  const key = deriveKey();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const ciphertext = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  return [
    ENC_PREFIX,
    iv.toString("base64"),
    authTag.toString("base64"),
    ciphertext.toString("base64"),
  ].join("$");
};

/**
 * Decrypt a value produced by encryptSecret. Returns null on any malformed or
 * tampered input rather than throwing, so a corrupt stored key degrades to
 * "no DB key" instead of crashing the request.
 */
export const decryptSecret = (stored: string | null | undefined): string | null => {
  if (!stored) return null;
  const parts = stored.split("$");
  if (parts.length !== 4 || parts[0] !== ENC_PREFIX) return null;
  try {
    const key = deriveKey();
    const iv = Buffer.from(parts[1], "base64");
    const authTag = Buffer.from(parts[2], "base64");
    const ciphertext = Buffer.from(parts[3], "base64");
    const decipher = crypto.createDecipheriv("aes-256-gcm", key, iv);
    decipher.setAuthTag(authTag);
    const plaintext = Buffer.concat([
      decipher.update(ciphertext),
      decipher.final(),
    ]);
    return plaintext.toString("utf8");
  } catch {
    return null;
  }
};
